### ISSUE TITLE
401 error-recovery not working for controls

### ISSUE THREAD

**Issue by gigatexel** [astrandb/miele#285] opened 2023-06-19 06:25 UTC
### The problem

Occasionally, a 401 error thrown by the API makes the entities Unavailable but the integration seems to recover.

![image](https://github.com/astrandb/miele/assets/65073191/20b9d47b-7c83-41c5-9410-54857d0f619f)

However, the controls systematically don't recover. Only solution is to reload the integration after a 401.

![image](https://github.com/astrandb/miele/assets/65073191/f80cd7e0-e8f8-4a18-ab37-66ec896548b9)

### Version of miele integration having the issue?

0.1.14

### Version of Home Assistant Core having the issue?

2023.06.2

### Anything in the logs that might be useful for us?

```txt
-06-19 07:37:10.365 ERROR (MainThread) [custom_components.miele] Error fetching miele data: HTTP status 401: 1
```

**Comment by astrandb** [comment] 2023-06-19 07:55
Thank you for the report. Just to double-check - The sensors recover but the controls do not ?? 
The mechanism behind availability of buttons and switches requires that the API reports if they should be active or not. Please try to catch a diagnostic download if this situation occurs again.

**Comment by gigatexel** [comment] 2023-06-19 09:11
> Thank you for the report. Just to double-check - The sensors recover but the controls do not ?? The mechanism behind availability of buttons and switches requires that the API reports if they should be active or not. Please try to catch a diagnostic download if this situation occurs again.

Correct.

What do you need? Should I level up the logging on the integration?
Diagnostics report only shows the error shown above.

**Comment by aturri** [comment] 2023-06-19 09:21
Hi,
I've noticed the same issue in these days, but I didn't have time to check what happened. Next time it happens, I'll download diagnostic too.
Andrea

**Comment by astrandb** [comment] 2023-06-19 16:03
> What do you need? Should I level up the logging on the integration?
> Diagnostics report only shows the error shown above.

Please press Download Diagnostics as displayed screendump you show above. The generated file should contain a lot of goodies, including the latest data from the API.

**Comment by aturri** [comment] 2023-06-22 15:49
Hi,
I'm experiencing this problem right now, so I downloaded the diagnostic files.

The washer has controls that are all disabled, while the dryer is working properly.

Diagnostic of the washer: 
[miele-c56f9e04b768f7de38f25ee880223a28-Washing machine-abd5ae47b0536ff8254c394d56168b21.json.txt](https://github.com/astrandb/miele/files/11835895/miele-c56f9e04b768f7de38f25ee880223a28-Washing.machine-abd5ae47b0536ff8254c394d56168b21.json.txt)

Diagnostic of the dryer: 
[miele-c56f9e04b768f7de38f25ee880223a28-Tumble dryer-48d6ef1302d6573e489bbae76eabf944.json.txt](https://github.com/astrandb/miele/files/11835898/miele-c56f9e04b768f7de38f25ee880223a28-Tumble.dryer-48d6ef1302d6573e489bbae76eabf944.json.txt)

It is possible to see that washer has the action `powerOn` that is `false`, while it is `true` for the dryer.

Then, I reloaded the integration and this is now the diagnostic of the washer: 
[Uploading miele-c56f9e04b768f7de38f25ee880223a28-Washing machine-abd5ae47b0536ff8254c394d56168b21.json (1).txt…]()

Now `powerOn` is `true`. This confirms that the problem is on Miele API, after a 401, actions remain disabled when using server sent events. Reloading the integration forces a new SSE connection to establish and, then, correct actions.
Probably we could fix this by closing the old SSE connection after a 401 and open a new one. What do you think @astrandb ?

Thank you
Andrea

**Comment by aturri** [comment] 2023-06-22 15:51
However, in my case I can't find a 401 in my HA logs, but a temporary network outage:

```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.miele
Source: helpers/update_coordinator.py:229
Integration: Miele (documentation, issues)
First occurred: 10:34:10 (3 occurrences)
Last logged: 17:20:14

Timeout fetching miele data
Error requesting miele data: Cannot connect to host api.mcs3.miele.com:443 ssl:default [Network unreachable]
```

**Comment by woempiej** [comment] 2023-06-22 16:29
![afbeelding](https://github.com/astrandb/miele/assets/62903344/b34190b5-b5aa-4700-8aef-851029f79044)

**Comment by astrandb** [comment] 2023-06-28 08:11
> This confirms that the problem is on Miele API, after a 401, actions remain disabled when using server sent events. Reloading the integration forces a new SSE connection to establish and, then, correct actions. Probably we could fix this by closing the old SSE connection after a 401 and open a new one. What do you think @astrandb ?

@aturri Sorry for my late reply but I have been away from my desk for some days. It definitely looks like a problem in the API, though have not seen this problem in my installation (yet?).

My first thought was that we should report it to Miele. It could be interesting to see if the actions API is different from the SSE stream in this situation.
As a last resort we could restart the SSE stream, but the question is in what the trigger should be...

**Comment by astrandb** [comment] 2024-11-27 21:57
Stale issue - closing

**Closed by astrandb** 2024-11-27 21:57 UTC
Labels: bug, additional info requested
