### ISSUE TITLE
KMDA7476 KeyError: 'state|plateStep|4|value_raw'

### ISSUE THREAD

**Issue by Adi146** [astrandb/miele#133] opened 2022-09-02 08:09 UTC
### The problem

When adding my two in one hob to Home Assistant with the miele integration, I get following exception spamming the logs:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/miele/number.py:227
Integration: Miele (documentation, issues)
First occurred: 09:01:28 (58 occurrences)
Last logged: 09:48:45

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/miele/__init__.py", line 181, in _callback_update_data
    coordinator.async_set_updated_data(flat_result)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 354, in state
    return self.value
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 404, in value
    if (native_value := self.native_value) is None:
  File "/config/custom_components/miele/number.py", line 227, in native_value
    return PLATE_MAP[self.coordinator.data[self._ent][self._ed.data_tag]]
KeyError: 'state|plateStep|4|value_raw'
```
[miele-c59b8a464af2b0cb092b8c7edfa5c1fc-KMDA7476-aef9c6e748be6d680ed4a30cd3dcaabf.json.txt](https://github.com/astrandb/miele/files/9476115/miele-c59b8a464af2b0cb092b8c7edfa5c1fc-KMDA7476-aef9c6e748be6d680ed4a30cd3dcaabf.json.txt)

### Version of miele integration having the issue?

miele-v0.0.23

### Version of Home Assistant Core having the issue?

core-2022.8.7

**Comment by astrandb** [comment] 2022-09-02 09:56
Thank you for the report. I can see the root cause. Will be fixed.

**Comment by astrandb** [comment] 2022-09-02 10:06
As a workaround please test to disable the entity `Plate 4` on the device screen.

**Comment by Adi146** [comment] 2022-09-05 19:16
Thanks for the quick fix.
I just noticed that sometime the miele api does not return any `plateSteps` at all. I don't know when this is the case but I think this need some further adjustments. Here is another diagnostics info for this case.

[miele-773b0918d5bf6f481e1eafa216419768-KMDA7476-aef9c6e748be6d680ed4a30cd3dcaabf.json.txt](https://github.com/astrandb/miele/files/9491717/miele-773b0918d5bf6f481e1eafa216419768-KMDA7476-aef9c6e748be6d680ed4a30cd3dcaabf.json.txt)

**Comment by astrandb** [comment] 2022-09-05 19:57
OK, I just wish everything was stable...
The plate entities are first created when HA is started. In the current design they will not install if they appear later in the session. It will be a major redesign to pick up changes dynamically. However, if they are present when HA starts and then disappear they should be flagged as unavailable as long as they are gone. At least that is the intention.

**Comment by Adi146** [comment] 2022-09-05 20:17
Yeah the Miele API seems to be difficult to work with, especially when half of the stuff is not documented. However the behavior you described seems to work correctly. At least I get the same error as above when the plates disappear from the states json. When I understood you correctly it should go silently into unavailable shouldn't it?

**Comment by astrandb** [comment] 2022-09-05 20:28
Yes, it should be silent in the log. But that needs latest fix. I will doublecheck before release.

**Comment by Adi146** [comment] 2022-09-05 20:41
Ah my bad, I didn't realize that you made all of the plates optional. I thought you just adjusted the plate with index 4. So I think your fix should be sufficient. 

It looks like you can trigger the plates to appear by turning the hob on, so if someone has the same issue, just turn your hob on before adding it to home assistant should do the trick.

**Closed** 2022-09-07 07:18 UTC
Labels: bug
