### ISSUE TITLE
Home Assistant 2022.10

### ISSUE THREAD

**Issue by neildsb** [astrandb/miele#113] opened 2022-07-11 10:25 UTC
### The problem

Logger: homeassistant.components.number
Source: components/number/__init__.py:220
Integration: Number (documentation, issues)
First occurred: 11:17:27 am (4 occurrences)
Last logged: 11:17:51 am

custom_components.miele.number::MieleNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.deebot.number::VolumeEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.velux.number::VeluxOpenOrientatoion is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.velux.number::VeluxCloseOrientatoion is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

### Version of miele integration having the issue?

Future

### Version of Home Assistant Core having the issue?

2022.10

**Comment by astrandb** [comment] 2022-07-11 13:16
Duplicate of #110
Will be released within a few days

**Comment by woempiej** [comment] 2022-07-25 18:11
> Duplicate of #110 Will be released within a few days

Thank you for your effort!

**Comment by slyoldfox** [comment] 2022-08-20 15:43
@astrandb Any possiblities to release this or are you working on more features? (I'm cleaning up my warnings as well from the logs)

**Comment by astrandb** [comment] 2022-08-24 16:36
Released in v0.0.23

**Closed by astrandb** 2022-08-24 16:36 UTC
Labels: bug, duplicate
