### ISSUE TITLE
Bug: 'Miele' integration interferring somehow with other integration(s) ('Logitech Harmony' integration in this case)

### ISSUE THREAD

**Issue by Grandma-Betty** [astrandb/miele#577] opened 2024-11-03 17:24 UTC
### The problem

I just installed the Miele integration for the very first time.
The Miele integration functionality works as intended.
However, after installing the Miele integration from HACS, as soon as the Miele device gets auto-discovered by HA, the Logitech Harmony integration does not work anymore and shows the following message:

![Screenshot 2024-11-03 175709](https://github.com/user-attachments/assets/86dfa532-0eab-42ea-933d-2e8c5a9aa7bd)

When I try to relaod and reconfigure the Logitech Harmony integration, I get the following:

![Screenshot 2024-11-03 175730](https://github.com/user-attachments/assets/26622257-4af3-42cd-a32a-7ddb053b4bdc)

It seems the Miele integration does interferre somehow with the Logitech Harmony integration but I was not able to find out what the issue is. I can definitely reproduce this behaviour anytime. I tried the 2024.8.1 and also the latest 2024.9.0b1 version of the Miele integration.

Please have also a look on the error logs attached.

I am aware that the logs do not come from the Miele integration but the interferring issue is definitely being triggered by the Miele integration so I hope you could at least give some advice what the potential issue could be.

Thanks a bunch in advance!

[1.txt](https://github.com/user-attachments/files/17611357/1.txt)
[2.txt](https://github.com/user-attachments/files/17611358/2.txt)
[3.txt](https://github.com/user-attachments/files/17611359/3.txt)

### Version of miele integration having the issue?

miele-2024.8.1

### Version of Home Assistant Core having the issue?

core-2024.10.4

**Comment by astrandb** [comment] 2024-11-03 17:50
This bug is not really related to the Miele integration, but it can obviously trigger something.
The root cause is a breaking change in an upstream library that is used by Harmony. It is fixed in HA 2024.11.0b2. The official release is due on upcoming wednesday.
Read more: https://github.com/home-assistant/core/pull/129592

**Closed as completed** 2024-11-03 19:15 UTC
Labels: bug
